config:
  build-dir: ./build/snippet
  ignore:
    - '*.md'
    - 'print.hpp'

snippet:
  - data-structure: src/data-structure/
  - debug: src/debug/
  - graph: src/graph/
  - math: src/math/
  - snippets: src/snippets/
  - string: src/string/
  - template: src/template/
  - utils: src/utils/

scope:
  cpp: 'cpp'
  hpp: 'cpp'
  ipp: 'cpp'
  py: 'py'
